apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace}}
  labels:
    source: {{ .Values.labels.source }}
    stack: {{ .Values.labels.stack }}
    app: {{ .Values.labels.app }}
spec:
  replicas: {{ .Values.replicacount }}
  selector:
    matchLabels:
      source: {{ .Values.matchLabels.source }}
      app: {{ .Values.matchLabels.app }}
  template:
    metadata:
      labels:
        source: {{ .Values.labels.source }}
        app: {{ .Values.labels.app }}
    spec:
      containers:
      - name: maven-container
        image: {{ .Values.image.repository }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.containerPort }}

---

kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace}}
spec:
  selector:
    source: {{ .Values.labels.source }}
    app: {{ .Values.labels.app }}
  type: {{ .Values.service.type }}
  ports:
  - protocol: {{ .Values.service.protocol }}
    port: {{ .Values.containerPort }}
    nodePort: {{ .Values.service.nodeport }}
    targetPort: {{ .Values.containerPort }}
