apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-demo
  namespace: {{ .Release.Namespace}}
  labels:
    source: maven
    stack: frontend
    app: tomcat
spec:
  replicas: 2
  selector:
    matchLabels:
      source: maven
      app: tomcat
  template:
    metadata:
      labels:
        source: maven
        app: tomcat
    spec:
      containers:
      - name: maven-container
        image: "{{ .Values.image.repository }}::{{ .Values.image.tag}}"
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: maven-demo
  namespace: dev
spec:
  selector:
    source: maven
    app: tomcat
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    nodePort: {{ .Values.service.targetport }}
    targetPort: 8080